### ISSUE TITLE
[BUG]: Latest v0.17.0 delivers no information on entered gcode

### ISSUE THREAD

**Issue by fnsign** [costas-basdekis/MarlinGcodeDocumentation#20]
Hi,
I installed the latest 0.17.0 release and discovered following bug:
When I enter a gcode (e.g. G28), M-command or ?phrase I receive the error message `Unknown Command`, no matter which source I select.
The attached log file shows, that there is a problem with the plugin.
[octoprint-13.log](https://github.com/costas-basdekis/MarlinGcodeDocumentation/files/8680527/octoprint-13.log)

**Comment by andrewseago** [comment]
Same issue here. Tried multiple uninstall and reinstall methods. Reinstalling 0.16 however works as expected.

**Comment by Shadow27374** [comment]
I haven't even tried that yet. But for me, the display has now moved to the bottom and is visible on every page. I personally find this very annoying.

**Comment by CitizenStile** [comment]
Also getting the same issue, uninstall/reinstall did not work. However manually installing 0.16 worked as others have said.

**Comment by valemaio2** [comment]
I can confirm too that the newest version doesn't display any help for any Marlin commands, and had to manually reinstall version 0.16. If you don't know how to, remove the plugin from the plugin manager (remove all data too when prompted by Octoprint), then go to the spanner settings on the top right, plugin manager, get more, and in the From URL field paste this link:

https://github.com/costas-basdekis/MarlinGcodeDocumentation/archive/refs/tags/v0.16.0.zip

which is basically the zip file for version 0.16.

**Comment by ssirkakriss** [comment]
Same issue for me as well, no info where it should be.

**Comment by costas-basdekis** [comment]
Thanks for the report everyone! Really sorry for the break.

If you open the options for the plug-in, there should be a section about downloading the definitions periodically.

What is the last update date there? What happens if you click on "Update now?"

I'm away, so won't be able to fix this week but will try to reproduce and fix next week

**Comment by fnsign** [comment]
If I click the `Update now` or `Reload` nothing happens and ther is also no date for `Last updated`. When I return to the terminalafter clickting the update button, there is still no information available.

The given documentation URL seems to work. When I enter it into my browser then the json file is displayed.

**Comment by PowerWiesel** [comment]
there seems to be in issue after fetching the new documentation file:

```
2022-05-17 23:53:08,244 - octoprint.plugins.marlingcodedocumentation - INFO - Updating GCode documentation...
2022-05-17 23:53:08,249 - octoprint.plugins.marlingcodedocumentation - INFO -  * Fetching https://raw.githubusercontent.com/costas-basdekis/gcode-documentation-parser/output/output/all_codes.json
2022-05-17 23:53:08,457 - octoprint.plugins.marlingcodedocumentation - INFO -  * Saving update (719883 bytes)
2022-05-17 23:53:08,460 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin marlingcodedocumentation
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 154, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_marlingcodedocumentation/__init__.py", line 139, in on_api_command
    self.update_documentation()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_marlingcodedocumentation/__init__.py", line 123, in update_documentation
    new_all_codes_path.write_text(contents)
  File "/usr/lib/python3.7/pathlib.py", line 1218, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.7/pathlib.py", line 1186, in open
    opener=self._opener)
  File "/usr/lib/python3.7/pathlib.py", line 1039, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: 'new-all_codes.json'
```

**Comment by costas-basdekis** [comment]
@PowerWiesel that seems to be exactly the issue! Thank you for the logs.

I'll fix within the weekend. Please downgrade the version for now

**Comment by costas-basdekis** [comment]
Hello, I have a release, and I'd like someone that had this issue to test a pre-release version, to verify that everything works correctly.

Would someone be willing to do that?

1. Switch to the virtual env for OctoPrint if you have one
2. Double-check that the plugin is already installed: `pip freeze | grep -i documentation`
3. Install the pre-release: `pip install git+https://github.com/costas-basdekis/MarlinGcodeDocumentation@v0.18.0#egg=Marlin_GCode_Documentation`
4. Restart your server
5. Refresh the page
6. Check the plugin's settings page `Last update status` value
    * If that text is not there, you probably didn't install it properly, or in the wrong virtual env
    * If that text is there but with no value, refresh page, or click on `Update cache` and then refresh the page

If all is good, I'll make it an official release

**Comment by valemaio2** [comment]
I've installed the 0.18 version, but not via pip, as support for Python2.7 has been dropped with the latest Octoprint update, and the installation didn't work with pip3; I've installed it manually the same way I've reverted back to 0.16 (see my comment above).

Octoprint shows that I'm running version 0.18 of the plugin (which is expected), and so far it seems to be working, both for explaining single commands and for searching for commands (as in **?home** for example). I will keep testing it as I use it extensively, and will report back if there's any issue
![Plugin version](https://user-images.githubusercontent.com/72505627/169556464-e375b069-5766-4b8d-b3e5-a8e9b6b18851.PNG)
![Plugin working in the GUI](https://user-images.githubusercontent.com/72505627/169556469-94ebb0c7-3de3-4d09-a58d-70e897cbac06.PNG)
.

**Comment by PowerWiesel** [comment]
I updated the plugin the way you requested it and the issue seems to be fixed :partying_face: 

Thank you very much :+1: 
![Bildschirmfoto vom 2022-05-20 17-45-57](https://user-images.githubusercontent.com/11167590/169564911-716fe5ab-013f-42e3-9bab-b1820d981ca6.png)
![Bildschirmfoto vom 2022-05-20 17-46-14](https://user-images.githubusercontent.com/11167590/169564922-cbe20454-65d4-42b9-9e1b-097e134cacff.png)

```
pi@octopi:~ $ source oprint/bin/activate
(oprint) pi@octopi:~ $ pip freeze | grep -i documentation
Marlin-GCode-Documentation @ https://github.com/costas-basdekis/MarlinGcodeDocumentation/archive/v0.17.0.zip
(oprint) pi@octopi:~ $ pip install git+https://github.com/costas-basdekis/MarlinGcodeDocumentation@v0.18.0#egg=Marlin_GCode_Documentation
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting Marlin_GCode_Documentation
  Cloning https://github.com/costas-basdekis/MarlinGcodeDocumentation (to revision v0.18.0) to /tmp/pip-install-s2xbmf5k/marlin-gcode-documentation_d77ad2c9e04d4ad28d1b04707bcea4cb
Requirement already satisfied: OctoPrint in ./oprint/lib/python3.7/site-packages (from Marlin_GCode_Documentation) (1.8.0)
Requirement already satisfied: sarge==0.1.6 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (0.1.6)
Requirement already satisfied: markdown<4,>=3.2.2 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (3.3.6)
Requirement already satisfied: pkginfo<2,>=1.7.1 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (1.8.2)
Requirement already satisfied: watchdog<2,>=1 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (1.0.2)
Requirement already satisfied: pylru<2,>=1.2 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (1.2.0)
Requirement already satisfied: pyserial<4,>=3.4 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (3.5)
Requirement already satisfied: Flask-Login<0.6,>=0.5 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (0.5.0)
Requirement already satisfied: pathvalidate<3,>=2.4.1 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (2.5.0)
Requirement already satisfied: colorlog<7,>=6 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (6.6.0)
Requirement already satisfied: unidecode in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (0.4.21)
Requirement already satisfied: zeroconf<0.34,>=0.33 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (0.33.4)
Requirement already satisfied: cachelib<0.3,>=0.2 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (0.2.0)
Requirement already satisfied: OctoPrint-FirmwareCheck>=2021.10.11 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (2021.10.11)
Requirement already satisfied: zipstream-ng<2.0.0,>=1.3.4 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (1.3.4)
Requirement already satisfied: Click<9,>=8.0.3 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (8.1.2)
Requirement already satisfied: netifaces<1,>=0.11 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (0.11.0)
Requirement already satisfied: wrapt<1.14,>=1.13.3 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (1.13.3)
Requirement already satisfied: websocket-client<2,>=1.2.1 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (1.3.2)
Requirement already satisfied: filetype<2,>=1.0.7 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (1.0.7)
Requirement already satisfied: PyYAML<6,>=5.4.1 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (5.4.1)
Requirement already satisfied: Flask-Babel<3,>=2.0 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (2.0.0)
Requirement already satisfied: emoji<2,>=1.4.2 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (1.7.0)
Requirement already satisfied: requests<3,>=2.26.0 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (2.27.1)
Requirement already satisfied: sentry-sdk<2,>=1.5.7 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (1.5.8)
Requirement already satisfied: psutil<6,>=5.8 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (5.8.0)
Requirement already satisfied: Flask-Assets<3,>=2.0 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (2.0)
Requirement already satisfied: regex in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (2020.11.13)
Requirement already satisfied: future<1,>=0.18.2 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (0.18.2)
Requirement already satisfied: OctoPrint-PiSupport>=2022.3.28 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (2022.3.28)
Requirement already satisfied: werkzeug<2.1,>=2.0 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (2.0.3)
Requirement already satisfied: blinker<2,>=1.4 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (1.4)
Requirement already satisfied: flask<3,>=2 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (2.1.1)
Requirement already satisfied: tornado<7,>=6.0.4 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (6.1)
Requirement already satisfied: semantic-version<3,>=2.8.5 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (2.8.5)
Requirement already satisfied: frozendict<3,>=2.0 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (2.3.1)
Requirement already satisfied: OctoPrint-FileCheck>=2021.2.23 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (2021.2.23)
Requirement already satisfied: feedparser<7,>=6.0.8 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (6.0.8)
Requirement already satisfied: netaddr<0.9,>=0.8 in ./oprint/lib/python3.7/site-packages (from OctoPrint->Marlin_GCode_Documentation) (0.8.0)
Requirement already satisfied: importlib-metadata in ./oprint/lib/python3.7/site-packages (from Click<9,>=8.0.3->OctoPrint->Marlin_GCode_Documentation) (4.11.3)
Requirement already satisfied: sgmllib3k in ./oprint/lib/python3.7/site-packages (from feedparser<7,>=6.0.8->OctoPrint->Marlin_GCode_Documentation) (1.0.0)
Requirement already satisfied: Jinja2>=3.0 in ./oprint/lib/python3.7/site-packages (from flask<3,>=2->OctoPrint->Marlin_GCode_Documentation) (3.1.1)
Requirement already satisfied: itsdangerous>=2.0 in ./oprint/lib/python3.7/site-packages (from flask<3,>=2->OctoPrint->Marlin_GCode_Documentation) (2.1.2)
Requirement already satisfied: webassets>=2.0 in ./oprint/lib/python3.7/site-packages (from Flask-Assets<3,>=2.0->OctoPrint->Marlin_GCode_Documentation) (2.0)
Requirement already satisfied: pytz in ./oprint/lib/python3.7/site-packages (from Flask-Babel<3,>=2.0->OctoPrint->Marlin_GCode_Documentation) (2020.5)
Requirement already satisfied: Babel>=2.3 in ./oprint/lib/python3.7/site-packages (from Flask-Babel<3,>=2.0->OctoPrint->Marlin_GCode_Documentation) (2.9.0)
Requirement already satisfied: typing-extensions>=3.6.4 in ./oprint/lib/python3.7/site-packages (from importlib-metadata->Click<9,>=8.0.3->OctoPrint->Marlin_GCode_Documentation) (4.1.1)
Requirement already satisfied: zipp>=0.5 in ./oprint/lib/python3.7/site-packages (from importlib-metadata->Click<9,>=8.0.3->OctoPrint->Marlin_GCode_Documentation) (3.8.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./oprint/lib/python3.7/site-packages (from Jinja2>=3.0->flask<3,>=2->OctoPrint->Marlin_GCode_Documentation) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in ./oprint/lib/python3.7/site-packages (from requests<3,>=2.26.0->OctoPrint->Marlin_GCode_Documentation) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./oprint/lib/python3.7/site-packages (from requests<3,>=2.26.0->OctoPrint->Marlin_GCode_Documentation) (1.26.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./oprint/lib/python3.7/site-packages (from requests<3,>=2.26.0->OctoPrint->Marlin_GCode_Documentation) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in ./oprint/lib/python3.7/site-packages (from requests<3,>=2.26.0->OctoPrint->Marlin_GCode_Documentation) (2020.12.5)
Requirement already satisfied: ifaddr>=0.1.7 in ./oprint/lib/python3.7/site-packages (from zeroconf<0.34,>=0.33->OctoPrint->Marlin_GCode_Documentation) (0.1.7)
Building wheels for collected packages: Marlin-GCode-Documentation
  Building wheel for Marlin-GCode-Documentation (setup.py) ... done
  Created wheel for Marlin-GCode-Documentation: filename=Marlin_GCode_Documentation-0.18.0-py3-none-any.whl size=30386 sha256=4af64b2ee65b01b9b0a09a31ce8035553f4f9e21df7b8717d63524a6f7930cf4
  Stored in directory: /tmp/pip-ephem-wheel-cache-2lobegt5/wheels/58/c1/d5/ddf3088e2902f542cf072096dd6580fcfc39bd80a1e0ab20e3
Successfully built Marlin-GCode-Documentation
Installing collected packages: Marlin-GCode-Documentation
  Attempting uninstall: Marlin-GCode-Documentation
    Found existing installation: Marlin-GCode-Documentation 0.17.0
    Uninstalling Marlin-GCode-Documentation-0.17.0:
      Successfully uninstalled Marlin-GCode-Documentation-0.17.0
Successfully installed Marlin-GCode-Documentation-0.18.0
WARNING: You are using pip version 20.3.3; however, version 22.1 is available.
You should consider upgrading via the '/home/pi/oprint/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by costas-basdekis** [comment]
Thank you all, I've just released it, so feel free to update
